all: ../output/member_deference_nonapproval_geography_review_queue.csv \
	../output/member_deference_nonapproval_geography_chatgpt_review_responses.csv

../output/member_deference_nonapproval_geography_review_queue.csv:
	@test -s "$@"

../output/member_deference_nonapproval_geography_chatgpt_review_responses.csv:
	@test -s "$@"

link-inputs:

include ../../generic.make
