all: ../output/ulurp_modification_zap_document_links.csv \
	../output/ulurp_modification_zap_docket_text.csv

../output/ulurp_modification_zap_document_links.csv:
	@test -s "$@"

../output/ulurp_modification_zap_docket_text.csv:
	@test -s "$@"

link-inputs:

include ../../generic.make
