all: ../output/official_ulurp_cpc_document_validation_labels.csv \
	../output/official_ulurp_cpc_source_exception_labels.csv \
	../output/official_ulurp_cpc_narrative_boundary_exceptions.csv \
	../output/official_ulurp_cpc_short_page_validation.csv \
	../output/official_ulurp_cpc_external_reference_exclusions.csv

../output/official_ulurp_cpc_document_validation_labels.csv:
	@test -s "$@"

../output/official_ulurp_cpc_source_exception_labels.csv:
	@test -s "$@"

../output/official_ulurp_cpc_narrative_boundary_exceptions.csv:
	@test -s "$@"

../output/official_ulurp_cpc_short_page_validation.csv:
	@test -s "$@"

../output/official_ulurp_cpc_external_reference_exclusions.csv:
	@test -s "$@"

link-inputs:

include ../../generic.make
