all: ../output/zap_outcome_usability_by_period.csv \
	../output/zap_source_integrity_qc.csv

../output/zap_outcome_usability_by_period.csv:
	@test -s "$@"

../output/zap_source_integrity_qc.csv:
	@test -s "$@"

link-inputs:

include ../../generic.make
