all: ../output/ulurp_cpc_kwic_calibration_labels.csv \
	../output/ulurp_cpc_initial_event_labels.csv \
	../output/ulurp_cpc_event_validation_labels.csv \
	../output/ulurp_cpc_community_district_corrections.csv

../output/ulurp_cpc_kwic_calibration_labels.csv:
	@test -s "$@"

../output/ulurp_cpc_initial_event_labels.csv:
	@test -s "$@"

../output/ulurp_cpc_event_validation_labels.csv:
	@test -s "$@"

../output/ulurp_cpc_community_district_corrections.csv:
	@test -s "$@"

link-inputs:

include ../../generic.make
