all: ../output/ulurp_cpc_source_corrections.csv \
	../output/ulurp_cpc_index_additions.csv

../output/ulurp_cpc_source_corrections.csv:
	@test -s "$@"

../output/ulurp_cpc_index_additions.csv:
	@test -s "$@"

link-inputs:

include ../../generic.make
