all: ../output/ulurp_cpc_page_scope_reviews.csv ../output/ulurp_cpc_companion_reports.csv ../output/ulurp_cpc_source_corrections.csv \
	../output/ulurp_cpc_index_additions.csv \
	../output/ulurp_cpc_narrative_boundary_exceptions.csv \
	../output/ulurp_cpc_community_district_corrections.csv

link-inputs:

include ../../generic.make
